-- AlterTable
ALTER TABLE "Blog" ALTER COLUMN "userId" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "created_by" DROP NOT NULL,
ALTER COLUMN "created_by" DROP DEFAULT,
ALTER COLUMN "roles" DROP DEFAULT,
ALTER COLUMN "updated_by" DROP NOT NULL,
ALTER COLUMN "updated_by" DROP DEFAULT;
